### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by Kyzoku** [LunaPixelStudios/Fantasy-Realm#26]
### Describe the Bug

I don't believe it to necessarily be a bug, but I am getting quite a bit of low FPS spikes.  I have tried turning off any dynamic lighting, lowering entity and render distances, basically lowering and turning off everything in settings.  I have added the java executable into windows display settings and set as high performance.  I have tried turning off threaded optimization in Nvidia control settings.  I have tried installing additional mods that claim FPS improvements like Optifine and others but they just cause the pack to crash.  I've also tried adding various JVM arguments, but I try not using them as I don't fully understand them.  I only use the launcher to allocate a max of 12GB ram.

Anyone have any other ideas?

System
AMD Ryzen 7 3700X
32GB Dual-Channel DDR4
NVIDIA GeForce RTX 2060
1TB Sabrent Rocket Q M.2 SSD

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

7

### Optifine

No

**Comment by chorbintime** [comment]
From our Discord:
RAM Allocation/Performance Guide

1) Open Task Manager (Ctrl + Shift + Escape)
2) Go to the Performance tab at the top
3) find the number under Memory (For example 5.8/7.9GB means your device has 8GB. 7.4/15.9GB means you have 16GB)

If you have 12GB or more, allocate 8000MB of RAM to Minecraft. 
If you have 8GB, allocate between 5000MB and 5500MB of RAM to Minecraft.

To allocate ram on CurseForge, use this tutorial: https://www.youtube.com/watch?v=P3hd9MKWvXw&t=130s
For other launchers, a Google search should help, or you can ask here.

If you are still experiencing lag, press F3 on your keyboard and check the percentage next to "Mem:". If it shows your game is using most of the RAM you've allocated, feel free to allocate more. Try not adding too much, as Minecraft can sometimes perform worse with too much ram. Also, make sure you leave 2-3 GB for Windows to run - otherwise your game performance will decrease. 

If your Memory is at high usage and Discord, Google, Overwolf, Curseforge, or other programs which are using lots of memory are open, close them via task manager (Press CTRL + Shift + Escape.) Just be sure not to close anything essential for your computer to run. 

Playing on one of the community-servers reduces the work your computer has to do, resulting in better performance. 

If you are playing a 1.16.5 modpack, you can uninstall Java 8 and install Java 11 from here https://adoptium.net/temurin/releases/?version=11. Install & run the .ms1 file if you are on Windows. Adoptium releases of Java are much more optimized and have no known memory leaks. The same applies for 1.18.2 and 1.19.2, except you will need Java 17 instead.

Setting Minecraft to high priority can result in minor FPS improvements. A tutorial can be found here https://www.youtube.com/watch?v=j1Rtd8JiClA 

If you wish to mess with java arguments, I suggest this guide https://github.com/TheUsefulLists/UsefulMods/blob/main/JavaArgumentsOptimization.md. Note that custom java arguments can worsen performance, so note FPS before & after. 

If you want to optimize Windows 10 as a whole, I can personally vouch for this video https://www.youtube.com/watch?v=sJrRB02xioI (most parts should also apply to other versions of Windows)

If you are using Windows 11, this short guide from Microsoft is worth a read: https://prod.support.services.microsoft.com/en-us/windows/options-to-optimize-gaming-performance-in-windows-11-a255f612-2949-4373-a566-ff6f3f474613

Better Minecraft Plus requires 8 GB or there will be, at best, minor lag.

Some additional things you can do to increase FPS, but can cause unwanted side effects. These should be last resort:
1) This will only work on Forge versions. 
Press escape ingame, click Mods, search Forge, click forge-client, and enable Force Threaded Chunk Rendering. This can result in worse FPS or much higher FPS, so it's best to check your FPS before and after.
2) Remove the Dynamic Lights mod. If you are playing Fabric, this mod may be called LambDynamicLights. On Forge, it may be called Dynamic Lights Reforged.
3) Remove Oculus if you aren't using shaders. If you are playing Fabric, the mod is called Iris.
4) Remove the Simple Discord Rich Presence mod (goes by several names). You can also remove the Bisect Hosting Menu mod. Removing these mods are very unlikely to improve your FPS but, as I said, these are last resort options.

**Comment by Kyzoku** [comment]
Thank you very much for that info.  I decided to switch to the OpenJDK that was linked and used Aikar's flags from the JVM link.  I have only had a couple barely noticeable micro-stutters.  You're awesome!
